on:
  push:
    paths:
      - 'resources/js/*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: yarn build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: yarn install
      - run: yarn run production
